name: mjesec_po_mjesec
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/

  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # or latest

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
